# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.7

# Install the codecov pip dependency
install: pip3 install --upgrade pip

# Run the unit test
script: python3 leap.py || python leap.py
